kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
          namespace: javaproject
          name: deployment-manager
rules:
- apiGroups: ["","extensions","apps"] # "" indicates the core API group
  resources: ["pods","deployments","replicasets"]
  verbs: ["get", "watch", "list","create","delete","patch"] #you can also use ["*"]
